# Generated by Django 5.0.6 on 2024-07-03 11:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Aiapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SpeechRecognition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('original_text', models.TextField()),
                ('language_code', models.CharField(max_length=10)),
                ('recognized_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Translation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('translated_text', models.TextField()),
                ('target_language_code', models.CharField(max_length=10)),
                ('translated_at', models.DateTimeField(auto_now_add=True)),
                ('speech_recognition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Aiapp.speechrecognition')),
            ],
        ),
        migrations.DeleteModel(
            name='Resume',
        ),
    ]
